name: Update
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/60 * * * *"

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - name: Update
        run: |
          git clone --mirror https://gitlab.com/jeseibel/distant-horizons.git
          cd distant-horizons
          git remote set-url --push origin https://github.com/Jab125/Distant-Horizons-Mirror
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch -p origin
          git push --mirror