name: Update
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/60 * * * *"

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update
        run: |
          git clone --mirror https://gitlab.com/jeseibel/distant-horizons.git